//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanEduSlide.OEDongBo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_CongNo
    {
        public Nullable<System.DateTime> NgayLenDon { get; set; }
        public string MaHV { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string MaDonHang { get; set; }
        public string MaNVChotSale { get; set; }
        public string ChotSale { get; set; }
        public Nullable<double> ThangHocDuKien { get; set; }
        public string ChiNhanh { get; set; }
        public Nullable<System.DateTime> DateImport { get; set; }
    }
}
