//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanEduSlide.OEDongBo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_PhieuThu
    {
        public long PhieuThuKeToan { get; set; }
        public string ChiNhanh { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string Loai { get; set; }
        public string ReceiptCode { get; set; }
        public string MaHV { get; set; }
        public string TenHV { get; set; }
        public Nullable<decimal> TUD { get; set; }
        public Nullable<decimal> SUD { get; set; }
        public Nullable<double> PhanTramUD { get; set; }
        public string GioiTinh { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string Notes { get; set; }
        public string DangKy { get; set; }
        public Nullable<System.DateTime> GioTao { get; set; }
        public string MaNVChotSale { get; set; }
        public string ChotSale { get; set; }
        public string CongTacVien { get; set; }
        public Nullable<int> ThangHocDuKien { get; set; }
        public string UD_FINAL { get; set; }
        public string LoaiCTH { get; set; }
        public string ChuongTrinhHoc { get; set; }
        public string CapDo { get; set; }
        public string Modun { get; set; }
        public string UD_NhomUDFINAL { get; set; }
        public Nullable<long> HDBH { get; set; }
        public string DonHang { get; set; }
        public string UDPhieuThu { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhat { get; set; }
        public string TrangThai { get; set; }
        public int ID_StudentDept { get; set; }
    }
}
