//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanEduSlide.OEDongBo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DongBoTuyenSinhEntities : DbContext
    {
        public DongBoTuyenSinhEntities()
            : base("name=DongBoTuyenSinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BC_PhieuThu> BC_PhieuThu { get; set; }
        public virtual DbSet<DSNhanSuNguon> DSNhanSuNguons { get; set; }
        public virtual DbSet<QuaTrinhCongTac> QuaTrinhCongTacs { get; set; }
        public virtual DbSet<ThaiSan> ThaiSans { get; set; }
        public virtual DbSet<BC_CongNo> BC_CongNo { get; set; }
    }
}
