//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanEduSlide.OEDongBo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSNhanSuNguon
    {
        public System.Guid IDNhanSuHRM { get; set; }
        public string MaNhanSu { get; set; }
        public string TenNhanSu { get; set; }
        public string ChiNhanh { get; set; }
        public string ChucDanhChuyenMon { get; set; }
        public string MaChucDanhChuyenMon { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayNghiViec { get; set; }
    }
}
