//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanEduSlide.OEDongBo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThaiSan
    {
        public System.Guid IDNhanSuHRM { get; set; }
        public System.DateTime NgayBatDauNghiThaiSan { get; set; }
        public System.DateTime NgayKetthucNghiThaiSan { get; set; }
    }
}
