// <auto-generated />
namespace OceanEduSlide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class office : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(office));
        
        string IMigrationMetadata.Id
        {
            get { return "202505060358096_office"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
