// <auto-generated />
namespace OceanEduSlide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RevenueUser_Month_BM_real : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevenueUser_Month_BM_real));
        
        string IMigrationMetadata.Id
        {
            get { return "202507180843577_RevenueUser_Month_BM_real"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
